insert into specialita (idspecialita, nome, immagine, esempi, status) values ('1', 'amico degli animali', 'spec/lc/amicodeglianimali.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('2', 'amico del mare', 'spec/lc/amicodelmare.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('3', 'amico della natura', 'spec/lc/amicodellanatura.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('4', 'amico di aronne', 'spec/lc/amicodiaronne.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('5', 'amico di samuele', 'spec/lc/amicodisamuele.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('6', 'amico di san francesco', 'spec/lc/amicodisanfrancesco.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('7', 'artigiano', 'spec/lc/artigiano.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('8', 'astronomo', 'spec/lc/astronomo.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('9', 'atleta', 'spec/lc/atleta.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('10', 'attore', 'spec/lc/attore.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('11', 'botanico', 'spec/lc/botanico.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('12', 'canterino', 'spec/lc/canterino.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('13', 'cercatore di tracce', 'spec/lc/cercatoreditracce.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('14', 'cittadino del mondo', 'spec/lc/cittadinodelmondo.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('15', 'collezionista', 'spec/lc/collezionista.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('16', 'cuoco', 'spec/lc/cuoco.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('17', 'disegnatore', 'spec/lc/disegnatore.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('18', 'folclorista', 'spec/lc/folclorista.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('19', 'fotografo', 'spec/lc/fotografo.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('20', 'giardiniere', 'spec/lc/giardiniere.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('21', 'giocatore di squadra', 'spec/lc/giocatoredisquadra.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('22', 'giocattolaio', 'spec/lc/giocattolaio.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('23', 'giornalista', 'spec/lc/giornalista.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('24', 'guida', 'spec/lc/guida.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('25', 'infermiere', 'spec/lc/infermiere.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('26', 'kim', 'spec/lc/kim.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('27', 'maestro dei giochi', 'spec/lc/maestrodeigiochi.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('28', 'maestro dei boschi', 'spec/lc/maestrodeiboschi.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('29', 'maestro della salute', 'spec/lc/maestrodellasalute.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('30', 'mani abili', 'spec/lc/maniabili.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('31', 'massaio', 'spec/lc/massaio.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('32', 'meteorologo', 'spec/lc/meteorologo.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('33', 'musicista', 'spec/lc/musicista.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('34', 'ripara-ricicla', 'spec/lc/ripara-ricicla.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('35', 'sarto', 'spec/lc/sarto.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('36', 'scaccia pericoli', 'spec/lc/scacciapericoli.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('37', 'scrittore', 'spec/lc/scrittore.jpg', NULL, '1');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('68', 'allevatore', 'spec/allevatore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('69', 'alpinista', 'spec/alpinista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('70', 'amico degli animali', 'spec/amicodeglianimali.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('71', 'amico del quartiere', 'spec/amicodelquartiere.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('72', 'archeologo', 'spec/archeologo.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('73', 'artigiano', 'spec/artigiano.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('74', 'artista di strada', 'spec/artistadistrada.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('75', 'astronomo', 'spec/astronomo.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('76', 'atleta', 'spec/atleta.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('78', 'attore', 'spec/attore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('79', 'batteliere', 'spec/batteliere.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('80', 'boscaiolo', 'spec/boscaiolo.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('81', 'botanico', 'spec/botanico.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('83', 'campeggiatore', 'spec/campeggiatore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('85', 'canoista', 'spec/canoista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('86', 'cantante', 'spec/cantante.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('87', 'carpentiere navale', 'spec/carpentierenavale.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('89', 'ciclista', 'spec/ciclista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('90', 'collezionista', 'spec/collezionista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('91', 'coltivatore', 'spec/coltivatore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('92', 'corrispondente', 'spec/corrispondente.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('93', 'corrispondente radio', 'spec/corrispondenteradio.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('94', 'cuoco', 'spec/cuoco.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('95', 'danzatore', 'spec/danzatore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('97', 'disegnatore', 'spec/disegnatore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('98', 'elettricista', 'spec/elettricista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('99', 'elettronico', 'spec/elettronico.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('100', 'esperto del computer', 'spec/espertodelcomputer.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('101', 'falegname', 'spec/falegname.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('102', 'fa tutto', 'spec/omnia.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('104', 'folclorista', 'spec/folclorista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('105', 'fotografo', 'spec/fotografo.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('107', 'giardiniere', 'spec/giardiniere.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('108', 'giocattolaio', 'spec/giocattolaio', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('109', 'grafico', 'spec/grafico.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('110', 'guida', 'spec/guida.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('111', 'guida marina', 'spec/guidamarina.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('112', 'hebertista', 'spec/hebertista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('113', 'idraulico', 'spec/idraulico', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('114', 'infermiere', 'spec/infermiere.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('115', 'interprete', 'spec/interprete.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('116', 'lavoratore in cuoio', 'spec/lavoratoreincuoio.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('117', 'maestro dei giochi', 'spec/maestrodeigiochi.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('118', 'maestro dei nodi', 'spec/maestrodeinodi.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('120', 'meccanico', 'spec/meccanico.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('121', 'modellista', 'spec/modellista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('123', 'muratore', 'spec/muratore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('124', 'musicista', 'spec/musicista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('125', 'naturalista', 'spec/naturalista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('127', 'nuotatore', 'spec/nuotatore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('128', 'osservatore', 'spec/osservatore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('129', 'osservatore meteo', 'spec/osservatoremeteo.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('130', 'pescatore', 'spec/pescatore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('131', 'pompiere', 'spec/pompiere.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('132', 'redattore', 'spec/redattore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('133', 'regista', 'spec/regista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('134', 'sarto', 'spec/sarto.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('135', 'scenografo', 'spec/scenografo.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('136', 'segnalatore', 'spec/segnalatore.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('137', 'servizio della parola', 'spec/serviziodellaparola.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('138', 'servizio liturgico', 'spec/servizioliturgico.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('139', 'servizio missionario', 'spec/serviziomissionario.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('142', 'europeista', 'spec/europeista.jpg', NULL, '2');
insert into specialita (idspecialita, nome, immagine, esempi, status) values ('143', 'topografo', 'spec/topografo.jpg', NULL, '2');
